esphome:
  name: battery-gauge
  friendly_name: Battery Gauge
  includes:
    - battery_gauge/display_draw.h
  on_boot:
    # Move the needle to the extremities and then settle on the battery's current SoC
    priority: -10
    then:
      - delay: 3s
      - servo.write:
          id: gauge_servo
          level: 0.0
      - delay: 800ms
      - servo.write:
          id: gauge_servo
          level: 1.0
      - delay: 800ms
      - servo.write:
          id: gauge_servo
          level: 0.5
      - delay: 800ms
      - if:
          condition:
            lambda: 'return id(battery_pct).has_state();'
          then:
            - servo.write:
                id: gauge_servo
                level: !lambda |-
                  float pct = id(battery_pct).state;
                  if (pct < 0) pct = 0;
                  if (pct > 100) pct = 100;
                  return 1.0f - (pct / 100.0f);

esp32:
  board: esp32dev
  framework:
    type: arduino

ota:
  - platform: esphome
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Battery-Gauge Fallback"
    password: !secret esphome_fallback_password

api:
  encryption:
    key: !secret esphome_battery_gauge_api_key

