sensor:
  - platform: homeassistant
    id: solar_power
    entity_id: sensor.10_hammond_way_solar_power_2

  - platform: homeassistant
    id: grid_power
    entity_id: sensor.10_hammond_way_grid_power_2

  - platform: homeassistant
    id: battery_pct
    entity_id: sensor.10_hammond_way_percentage_charged
    filters:
      - delta: 0.5
    on_value:
      then:
        - servo.write:
            id: gauge_servo
            level: !lambda |-
              float pct = x;
              if (pct < 0) pct = 0;
              if (pct > 100) pct = 100;
              return 1.0f - (pct / 100.0f);

  - platform: homeassistant
    id: batt_power
    entity_id: sensor.10_hammond_way_battery_power_2

  - platform: homeassistant
    id: reserve_pct
    entity_id: number.10_hammond_way_backup_reserve_2

globals:
  - id: mode_state
    type: int
    restore_value: no
    initial_value: "0"

  - id: flow_phase
    type: float
    restore_value: no
    initial_value: "0.0"